"""Added account table

Revision ID: 410761d30955
Revises: 
Create Date: 2023-02-27 14:56:15.123018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410761d30955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('code_word', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
