"""Added user table

Revision ID: a1dfec4ab6e5
Revises: 
Create Date: 2023-03-02 00:09:22.546669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1dfec4ab6e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=90), nullable=False),
    sa.Column('code', sa.String(length=90), nullable=True),
    sa.Column('diffie_hellman_key', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
